### ISSUE TITLE
Kernel installation procedure results in unbootable UEFI shell

### ISSUE THREAD

**Issue by paulmcauley** [eupnea-linux/mainline-kernel#7]
Hello, what is the complete procedure for installing this kernel properly?

Using a Lenovo C630 Chromebook with MrChromeBox coreboot 4.19 firmware, I have tried adding the rpm repo and installing the rpms under Fedora 38 using:  
`sudo dnf install eupnea-mainline-kernel.x86_64 eupnea-mainline-kernel-headers.x86_64 eupnea-mainline-kernel-modules.x86_64`

However, when I reboot I just get the UEFI shell and the system is unbootable.

I tried the same on OpenSUSE by manually downloading and then running the install-kernel script (and copying modules/headers) but this also resulted in the same UEFI shell screen.

**Comment by WeirdTreeThing** [comment]
You most likely need to create an initramfs image for the kernel.

**Comment by Apacelus** [comment]
All kernel install scripts are strictly for eupnea systems. They will overwrite the first partition on your drive.

Just follow some "install custom kernel" guide from the internet
